# Generated by Django 4.1.4 on 2022-12-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200, null=True)),
                ("questionID", models.IntegerField(null=True)),
                ("wpm", models.IntegerField(null=True)),
                ("fillerWords", models.CharField(max_length=500, null=True)),
                ("fillerPhrases", models.CharField(max_length=500, null=True)),
                ("recommendation", models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
